# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW9
pod 'Eureka', '~> 2.0.0-beta.1'
pod 'GooglePlacePicker'

  target 'HW9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HW9UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
